### ISSUE TITLE
Markdown needs update

### ISSUE THREAD

**Issue by anshumanv** [sindresorhus/electron-boilerplate#19]
The markdown used in license section from https://github.com/sindresorhus/electron-boilerplate/blob/master/boilerplate/readme.md needs update which currently is not displayed correctly.

Should I fix it ?

**Comment by sindresorhus** [comment]
That's intentional. You're supposed to fill out those placeholders yourself.

**Comment by anshumanv** [comment]
Thanks for the follow up, I missed the point that it was intentional.
