### ISSUE TITLE
Extra comma in readme

### ISSUE THREAD

**Issue by anshumanv** [sindresorhus/electron-boilerplate#20]
> Builds the app for macOS, Linux, and Windows, using electron-packager.  

Extra comma after `Linux`
in https://github.com/sindresorhus/electron-boilerplate/blob/master/boilerplate/readme.
Should this be fixed ?

**Comment by sindresorhus** [comment]
Oxford comma https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/
