### ISSUE TITLE
Download file link is broken

### ISSUE THREAD

**Issue by linoleum89** [sindresorhus/electron-boilerplate#23]
<img width="1270" alt="Screen Shot 2019-06-18 at 12 46 10 PM" src="https://user-images.githubusercontent.com/2753274/59710869-1a767100-91c7-11e9-8ab0-40299849bb76.png">

**Comment by notlmn** [comment]
The readme is a partial boilerplate that contains links which are supposed to be replaced when the boilerplate is used to build an actual application.

The link provided is to not download this boilerplate, use "download as zip" or "clone" option for that.

**Comment by linoleum89** [comment]
Oh yeah I was talking about for the direct link to the .dmg demo of what generares the boilerplate, not the code itself :)
