### ISSUE TITLE
Native Integration - How deep?

### ISSUE THREAD

**Issue by donaldpipowitch** [sindresorhus/electron-boilerplate#24]
Follow up from https://mobile.twitter.com/sindresorhus/status/1141380150593871877.

Hi! What do you typically do for native integration of your Electron apps. I know about handling light and dark themes, but what else? Do you also look at user/OS settings for font family/size, prefers-reduced-motion, system colors (e.g. to choose focus color), etc.?

Thank you and have a nice day :)

**Comment by sindresorhus** [comment]
This project is now archived.
