### ISSUE TITLE
Unhandled Promise Rejection - TypeError : Cannot read property "appId" of undefined

### ISSUE THREAD

**Issue by inkhsutesou** [sindresorhus/electron-boilerplate#31]
Using this boilerplate, if I attempt to generate a package for Windows, the process fails since the executable cannot access the app id in package.json.
https://github.com/sindresorhus/electron-boilerplate/blob/master/index.js#L17

**Comment by sindresorhus** [comment]
// @juliangruber

**Comment by juliangruber** [comment]
This error means that you don't have a `"build"` property in your `package.json`. If the `package.json` wasn't available, the `require('./package.json')` would have thrown.

**Comment by lomocc** [comment]
**"build"** property in **package.json** will be removed after **electron-builder**

**Comment by inkhsutesou** [comment]
@juliangruber Yes, it has the `build` property
@lomocc Electron-builder doesn't ship with `build` does the rest of `package.json` make it ?

Otherwise, out of the box, this boilerplate ships a failing package in Windows

**Comment by juliangruber** [comment]
I'm sorry about this, I hadn't tested it on Windows. If indeed electron-builder changes the `package.json` as part of the build process, it's best we revert https://github.com/sindresorhus/electron-boilerplate/commit/42644c3df92fec6650971ac3197b4426b3d98a69.

**Comment by igghera** [comment]
Is there a quick workaround, like downgrading to an older version? I need this working tomorrow and I can't build :(

**Comment by inkhsutesou** [comment]
@igghera 
```
app.setAppUserModelId( `Place User Model Id directly here` ); // or not, the application should still work if you never set a User Model Id
// app.setAppUserModelId( packageJson.build.appId );
```

**Comment by igghera** [comment]
@inkhsutesou thanks mate, you saved my life :)
and thanks to the maintainers of this repo, it's the best

**Comment by juliangruber** [comment]
PR up: https://github.com/sindresorhus/electron-boilerplate/pull/32

**Comment by moda20** [comment]
this repo still have this problem you know. the builder script removes the build subtree of package.json, you can't call anything from that without halting the launch of the app.

**Comment by sindresorhus** [comment]
@moda20 Where else are we calling something from the `build` directory?

**Comment by moda20** [comment]
It was on the top of the index.js file, it was a call to set the appId. the commit revert somehow brought back that line.
