### ISSUE TITLE
Menu Items to open function from other script/file

### ISSUE THREAD

**Issue by flattery103** [sindresorhus/electron-boilerplate#36]
It seems like bad practice to have other functions within the menu.js file. A menu item should be set up to run a function from main.js or a different functions.js file. 

Been banging my head on this one. What should be simple either isn't documented or isn't straight forward.

**Comment by sindresorhus** [comment]
I agree. On macOS, for example, they use the "responder chain", which makes it easy to dynamically decide what code handles certain menu items. The menu story on Electron is like most of Electron, not very well thought through.

If you want to split it up, I'd recommend using `ipc.invoke/handle`.

**Comment by sindresorhus** [comment]
This project is now archived.
